# Generated by Django 2.2 on 2020-11-13 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_auto_20201012_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 11, 13, 14, 7, 56, 693416), verbose_name='дата создания'),
        ),
    ]
