# Generated by Django 4.0 on 2023-04-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Продукт')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
