# Generated by Django 2.2 on 2020-11-13 14:07

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201102_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=movies.models.get_cover_path, verbose_name='Обложка'),
        ),
    ]
