# Generated by Django 3.0 on 2021-10-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название фильма')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genres.Genre')),
            ],
        ),
    ]
