# Generated by Django 4.0 on 2023-03-20 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата добавления'),
        ),
    ]
