# Generated by Django 4.0 on 2023-03-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_category_id_movie_category_movie_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='Название жанра'),
        ),
    ]
