# Generated by Django 4.0 on 2023-04-03 15:40

from django.db import migrations
from movies.models import Genre

CONST_GENRES = ('Детекив', 'Ужасы', 'Комедия', 'Приключения', 'Драма')

def forwards_func(apps, scheme_editor):
    for genre_name in CONST_GENRES:
        genre = Genre(name=genre_name)
        genre.save()

def reverse_func(apps, scheme_editor):
    for genre_name in CONST_GENRES:
        genre = Genre.objects.get(name=genre_name)
        genre.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_genre_name'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
