# Generated by Django 3.0 on 2021-10-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.TextField(unique=True, verbose_name='Название фильма'),
        ),
    ]
