# Generated by Django 3.0 on 2021-11-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20211018_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.ImageField(null=True, upload_to='', verbose_name='Обложка'),
        ),
    ]
