# Generated by Django 4.0 on 2023-04-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20230403_1540'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genre',
            table='genre',
        ),
    ]
