# Generated by Django 4.0 on 2023-04-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_genre_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genre',
            table=None,
        ),
    ]
