# Generated by Django 4.0 on 2023-04-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_genre_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('added_at',), 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Какая-то полезная информация о названии фильма.', max_length=64, null=True, verbose_name='Название фильма'),
        ),
    ]
